[changelog]
header = ""
body   = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits %}
- {{ commit.message | split(pat="\n") | first }} \
{% if commit.github.pr_number %}(#{{ commit.github.pr_number }}){% endif %}

{% endfor %}
{% endfor %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
commit_parsers = [
  { message = "^feat",     group = "Novidades"     },
  { message = "^fix",      group = "Correções"     },
  { message = "^perf",     group = "Performance"   },
  { message = "^refactor", group = "Refatoração"   },
  { message = "^docs",     group = "Documentação"  },
  { message = "^chore\\(version\\)", skip = true   },
  { message = "^chore",    group = "Manutenção"    },
]
tag_pattern = "v[0-9].*"
